### ISSUE TITLE
issue with IBM Java version to 1.8.0_sr6fp6 (8.0.6.6)

### ISSUE THREAD

**Issue by jchobantonov** [ibmruntimes/ci.docker#86]
following exception happens with version 8.0.6.6 when we run our web application:

```
ava.lang.NoSuchMethodError: sun/misc/IOUtils.readFully(Ljava/io/InputStream;IZ)[B (loaded from /opt/ibm/java/jre/lib/rt.jar by <Bootstrap Loader>) called from class java.lang.invoke.SecurityFrameInjector$1 (loaded from /opt/ibm/java/jre/lib/amd64/compressedrefs/jclSC180/vm.jar by <Bootstrap Loader>).
```

Indeed the rt.jar file that comes with 8.0.6.6 do not have the method sun.misc.IOUtils.readFully
The version 8.0.6.5 do not have this issue as the class sun.misc.IOUtils is having the method readFully

**Comment by jchobantonov** [comment]
here is the stacktrace:
```
java.lang.NoSuchMethodError: sun/misc/IOUtils.readFully(Ljava/io/InputStream;IZ)[B (loaded from /opt/ibm/java/jre/lib/rt.jar by <Bootstrap Loader>) called from class java.lang.invoke.SecurityFrameInjector$1 (loaded from /opt/ibm/java/jre/lib/amd64/compressedrefs/jclSC180/vm.jar by <Bootstrap Loader>).
 	at java.lang.invoke.SecurityFrameInjector$1.run(SecurityFrameInjector.java:103)
 	at java.lang.invoke.SecurityFrameInjector$1.run(SecurityFrameInjector.java:96)
 	at java.security.AccessController.doPrivileged(AccessController.java:678)
 	at java.lang.invoke.SecurityFrameInjector.initializeSecurityFrameClassBytes(SecurityFrameInjector.java:96)
 	at java.lang.invoke.SecurityFrameInjector.wrapHandleWithInjectedSecurityFrame(SecurityFrameInjector.java:132)
 	at java.lang.invoke.SecurityFrameInjector.wrapHandleWithInjectedSecurityFrameIfRequired(SecurityFrameInjector.java:210)
 	at java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:595)
 	at java.lang.invoke.MethodHandle.sendResolveMethodHandle(MethodHandle.java:1054)
 	at java.lang.invoke.MethodHandle.getCPMethodHandleAt(Native Method)
 	at java.lang.invoke.MethodHandle.getAdditionalBsmArg(MethodHandle.java:867)
 	at java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:946)
 	at org.glassfish.jersey.inject.hk2.JerseyClassAnalyzer.getConstructor(JerseyClassAnalyzer.java:172)
```

**Comment by jayasg12** [comment]
This is a known issue. we will be rolling out a fix for this . Thanks !!

**Comment by dinogun** [comment]
We have now rolled back to 8.0.6.5
